# This is a basic workflow to help you get started with Actions

name: End-to-end tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Cypress run
      - run: cypress-io/github-actions@v4
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
